package com.lata.demo.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
@ApiModel("This is Employee Entity having direct link with the Database table")
@Entity
public class Employee {
	@ApiModelProperty("This is autogenerated id for employee")
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int eid;
	@ApiModelProperty("This is for employee name")
	private String ename;
	public int getEid() {
		return eid;
	}
	public void setEid(int eid) {
		this.eid = eid;
	}
	public String getEname() {
		return ename;
	}
	public void setEname(String ename) {
		this.ename = ename;
	}
}
